# Generated by Django 4.1.5 on 2023-04-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estados_sesiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_sesion_id', models.IntegerField()),
                ('descripcion_estado_sesion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=150)),
                ('pais', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('doc_identidad_tipo', models.CharField(max_length=10)),
                ('doc_identidad_numero', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('domicilio', models.CharField(max_length=150)),
                ('telefono', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('fecha_alta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='paciente_estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('fecha_estado', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.IntegerField()),
                ('modalidad', models.CharField(max_length=20)),
                ('frecuencia', models.CharField(max_length=100)),
                ('tipo_contrato', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesional_id', models.IntegerField()),
                ('paciente_id', models.IntegerField()),
                ('valor_sesion', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_sesion', models.DateField()),
                ('estado_sesion_id', models.IntegerField()),
            ],
        ),
    ]
